language: go

go:
  - tip
  - 1.13.x

env:
  - GO111MODULE=on

before_script:
  - go get -v github.com/smallnest/syncx/...
  - go get github.com/mattn/goveralls

script:
  - go test -race -v .
  - goveralls -service=travis-ci

notifications:
  email:
    recipients: smallnest@gmail.com
    on_success: change
    on_failure: always
